### ISSUE TITLE
Stand-alone use is broken

### ISSUE THREAD

**Issue by vladshved** [debops/ansible-sysctl#12]
Using with ansible 2.3.1 in a `<project>/roles` by itself, without installing whole debops stuff, and got broken since last update:

`fatal: [<hostname>]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}`

**Comment by ypid** [comment]
Hi,

I would not say broken (it is not a bug, it is a feature, although I don’t use it because I think things should be done in the role without the need to patch it) 😉 

[Solution](https://www.google.com/search?q=%22lookup+plugin+(task_src)+not+found%22).

Ref: #10
