### ISSUE TITLE
Can not set keys 'net.ipv4.tcp_rfc1337' and 'net.ipv4.tcp_timestamps' in a OpenVZ container

### ISSUE THREAD

**Issue by pedroluislopez** [debops/ansible-sysctl#3]
```
root@xxxx:~# sysctl --system
* Applying /etc/sysctl.d/10-debops_sysctl.conf ...
kernel.shmall = 2097150
kernel.shmmax = 5368705024
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_ratelimit = 100
net.ipv4.icmp_ratemask = 88089
net.ipv4.ip_forward = 0
sysctl: permission denied on key 'net.ipv4.tcp_rfc1337'
sysctl: permission denied on key 'net.ipv4.tcp_timestamps'
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.accept_ra = 0
* Applying /etc/sysctl.d/30-ferm.conf ...
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.conf ...
```

`root@xxxx:~# source /etc/ansible/facts.d/cap12s.fact 
{"enabled": "true", "list": ["cap_chown", "cap_dac_override", "cap_dac_read_search", "cap_fowner", "cap_fsetid", "cap_kill", "cap_setgid", "cap_setuid", "cap_setpcap", "cap_linux_immutable", "cap_net_bind_service", "cap_net_broadcast", "cap_net_admin", "cap_net_raw", "cap_ipc_lock", "cap_ipc_owner", "cap_sys_chroot", "cap_sys_ptrace", "cap_sys_admin", "cap_sys_boot", "cap_sys_nice", "cap_sys_resource", "cap_sys_tty_config", "cap_mknod", "cap_lease", "cap_audit_write", "cap_setfcap+eip"]}`

**Comment by ypid** [comment]
Hm, I only tested/use LXC. According to `/etc/ansible/facts.d/cap12s.fact` the container has `cap_net_admin`. Do you see a possible check to not attempt to set those parameters in OpenVZ?

**Comment by pedroluislopez** [comment]
Yes, this is a solution because this parameters can be set in the host machine. 
How can we check if it is a OpenVZ container?

**Comment by ypid** [comment]
You could add something like:

```YAML
    state: '{{ sysctl__hardening_enabled|bool and
               not (ansible_virtualization_role == "guest" and ansible_virtualization_type == "openvz") | ternary("present", "absent") }}'
```

to the parameters which don’t work in OpenVZ.

**Comment by pedroluislopez** [comment]
I have done a PR: https://github.com/debops/ansible-sysctl/pull/4

**Comment by ypid** [comment]
Thanks. Merged.
