### ISSUE TITLE
`sysctl__swappiness` and `sysctl__vfs_cache_pressure` get permission denied on VPS

### ISSUE THREAD

**Issue by bryanbecker** [debops/ansible-sysctl#6]
The VPS provider I use doesn't allow setting these, but the failure causes ansible to abort.

Perhaps consider adding something like `|| true` to the task so it doesn't stop all debops?

removing `sysctl__paging_map` from the following in vars should work just as well, but might be smoother if the task "self recovered" from this 

```
sysctl__combined_parameters: '{{ sysctl__shared_memory_map
                                 | combine(sysctl__hardening_map)
                                 | combine(sysctl__parameters)
                                 | combine(sysctl__group_parameters)
                                 | combine(sysctl__host_parameters) }}'
```

**Comment by drybjed** [comment]
Try setting in the inventory for these hosts:
```
sysctl__paging_configure: False
```
This should disable swap configuration in the role.

**Comment by ypid** [comment]
@bryanbecker About the `|| true` thing: The role enforces every parameter but some parameters can not be changed in certain visualization systems. If you go through the [defaults](https://github.com/debops/ansible-sysctl/blob/master/defaults/main.yml) you will see some of those examples already (search for `ansible_`). Maybe you can open a PR and add such a condition for your circumstance?

**Comment by bryanbecker** [comment]
Thanks for the short one liner.

What about this simple change, just combining both of your suggestions?

**Comment by bryanbecker** [comment]
I should note:  I'm not really sure how to test this.  Any way to create an "openvz" environment inside a virtual machine?

**Comment by ypid** [comment]
@bryanbecker Sure there is but I guess you don’t need to go thought that. If you want containers on your own then LXC and optionally LXD is probably the way to go.
